
export const label = {
    ConfirmationMail: "Confirmation Mail",
    EnterEmail: "Enter your email address for verification.",
    Email: "Email",
    Send: "Send",
    EmailVerification: "Email Verification",
    EnterCode: 'Enter the 6-digit verification code send to your email address.',
    Proceed: "Proceed",
    Login: "Login",
    NoAccount: "Don’t have an account?",
    Signup: "Signup",
    Password: "Password",
    ForgotPassword: "Forgot password?",
    YouAgreeToOur: "By login , you agree to our",
    PrivacyPolicy: "Privacy Policy",
    And: "and",
    TermsAndConditions: "Terms & Conditions.",
    NewPassword: "New Password",
    EnterNewPasswordAndRemember: "Enter your new password and remember it.",
    EnterYourPassword: "Enter Your Password",
    ConfirmPassword: "Confirm Password",
    ConfirmYourPassword: "Confirm Your Password",
    PasswordDoNotMatch: "passwords do not match",
    UpdatePassword: "Update Password",
    NewPasswordSetSuccessfully: "New password set successfully",
    CongratulationsPasswordSetSuccessfully: "Congratulations! Your password has been set successfully. Please proceed to the login screen to verify your account.",
    Sign_Up: "Sign Up",
    AlreadyHaveAccount: "Already have an account?",
    Username: "Username",
    EnterYourUsername: "Enter Your Username",
    FirstName: "First Name",
    EnterYourFirstName: "Enter Your First Name",
    LastName: "Last Name",
    EnterYourLastName: "Enter Your Last Name",
    EnterYourEmail: "Enter Your Email",
    EnterVoucherCode: 'Enter Voucher Code',
    Apply: "Apply",
    MyCart: "My Cart",
    EstimatedTime7days: "Estimated time: 7 working days",
    OrderInfo: "Order Info",
    SubTotal: "subTotal",
    ShippingCost: "Shipping cost",
    Total: "Total",
    Checkout: "Checkout",
    AreYourSureYouWantToRemoveTheProductFromCart: 'Are you sure you want to remove product from the cart?',
    Yes: "Yes",
    No: "No",
    Back: "Back",
    Payment: "Payment",
    Review: "Review",
    PlaceOrder: "PlaceOrder",
    InvalidCardNumber: 'Invalid card number',
    CardHolderName: "Card Holder Name",
    EnterCardHolderName: "Enter card holder name",
    CardNumber: "Card Number",
    Expiration: "Expiration",
    MMYY: 'MM/YY',
    CVV: "CVV",
    Items: "Items",
    ShippingAddress: "ShippingAddress",
    Sub_Total: "Sub Total",
    FullName: "Full Name",
    MobileNumber: "Mobile Number",
    State: "State",
    City: "City",
    StreetAddress: "Street Address",
    PostalCode: "Postal Code",
    EnterFullName: "Enter Full Name",
    PhoneNumber: "Phone Number",
    State: "State",
    SelectState: "Select State",
    City: "City",
    SelectCity: "Select City",
    StreetAddress: "Street Address",
    EnterStreetAddress: "Enter Street Address",
    PostalCode: "Postal Code",
    EnterPostalCode: "Enter Postal Code",
    ContactUs: "Contact us",
    EnterYourName: "Enter Your Name",
    EnterYourSubject: "Enter Your Subject",
    EnterYourMessage: "Enter Your Message",
    Submit: "Submit",
    AboutUs: "About Us",
    MyOrders: "My Orders",
    Update: "Update",
    EnterNewPassword: "Enter New Password",
    EnterOldPassword: "Enter Old Password",
    ChangePassword: "Change Password",
    SaveChanges: "Save Changes",
    EditProfile: "Edit Profile",
    Profile: "Profile",
    SelectProductSize: "Please select Product size, color etc",
    Wishlist: "Wishlist",
    OpenDrawer: "Open drawer",
    OrderDetails: "Order Details",
    IAmHim: 'I’m Him',
    Quantity: "Quantity",
    UnitPrice: "Unit Price",
    OrderNumber: "Order Number",
    OrderDate: "Order Date",
    OrderStatus: "Order Status",
    Pending: "Pending",
    ShippingDetails: "Shipping Details",
    SubTotal: "Sub Total",
    Total: "Total",
    reviews: "reviews",
    Choose: "Choose",
    AddToCart: "Add to cart",
    Reviews: "Reviews",
    WriteYourReviews: "Write your reviews",
    AddReview: "Add Review",
    Shipping: "Shipping",
    InvalidPhoneNumber: "Invalid phone number",
    Status: "Status",
    TotalPrice: "Total Price",
    View: "View",
    HelloWelcomeBack: "Hello, Welcome Back",
    Categories: "Categories",
    seeAll: "see all",
    Credit: "Credit",
    Discover: "Discover",
    UploadPhoto: "Upload Photo",
    SelectAPhotoFrom: "Select a photo from", 
    Description: "Description"
}